import nodemailer from 'nodemailer'
import { Resend } from 'resend'
import env from '../../infrastructure/config/env.js'

// ทางเลือกที่ 1: Resend (แนะนำ - ใช้ API key จาก resend.com ไม่ต้องตั้ง SMTP)
const useResend = Boolean(env.resendApiKey)

// ทางเลือกที่ 2: SMTP (Outlook @cmu.ac.th, Gmail ฯลฯ)
const hasSmtpConfig = env.emailHost && env.emailUser && env.emailPass && env.emailFrom

// ใช้ mock mode เฉพาะเมื่อไม่มีทั้ง Resend และ SMTP หรือบังคับ USE_MOCK_EMAIL=true
const USE_MOCK_EMAIL = process.env.USE_MOCK_EMAIL === 'true' || (!useResend && !hasSmtpConfig)

// Resend client (เมื่อมี RESEND_API_KEY)
const resendClient = useResend ? new Resend(env.resendApiKey) : null

// Nodemailer transporter (เมื่อมี SMTP config — ไม่เรียกใช้เมื่อเลือก Resend อยู่ก่อนขั้นตอนส่ง)
const transporter = !USE_MOCK_EMAIL && hasSmtpConfig ? nodemailer.createTransport({
  host: env.emailHost,
  port: env.emailPort,
  secure: env.emailPort === 465,
  auth: {
    user: env.emailUser,
    pass: env.emailPass,
  },
  requireTLS: env.emailHost === 'smtp.gmail.com' || env.emailHost === 'smtp.office365.com',
  tls: { rejectUnauthorized: false },
  debug: false,
  logger: false,
}) : null

// Mock email function - แค่ log อีเมลออกมาใน console
const mockSendEmail = ({ to, subject, text, html }) => {
  const preview = (text || html || '')
    .replace(/<[^>]+>/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .substring(0, 160)
  console.log('[MOCK EMAIL] To:', to, '| Subject:', subject)
  console.log('[MOCK EMAIL] Preview:', preview)
  return {
    messageId: `mock-${Date.now()}@cmusharecycle.local`,
    accepted: [to],
    rejected: [],
    pending: [],
    response: '250 Mock email logged successfully',
  }
}

// ตรวจสอบการเชื่อมต่ออีเมล
export const verifyEmailConnection = async () => {
  if (USE_MOCK_EMAIL) {
    console.log('📧 Email Service: MOCK MODE (ไม่ส่งอีเมลจริง แค่ log ใน console)')
    return true
  }

  if (useResend && resendClient) {
    console.log('✅ Email Service: Resend (ส่งอีเมลจริง)')
    return true
  }

  if (!hasSmtpConfig) {
    console.error('❌ Email configuration not found')
    console.log('   ตั้งค่า Gmail: npm run email:gmail หรือใส่ EMAIL_HOST, EMAIL_USER, EMAIL_PASS, EMAIL_FROM ใน .env')
    return false
  }

  if (!transporter) {
    console.error('❌ Email transporter not initialized')
    return false
  }

  try {
    await Promise.race([
      transporter.verify(),
      new Promise((_, reject) =>
        setTimeout(() => reject(new Error('Email verification timeout (5s)')), 5000)
      )
    ])
    console.log('✅ Email Service: SMTP (Gmail → ส่งไป @cmu.ac.th ได้)')
    const maskUser = env.emailUser ? env.emailUser.replace(/(.{2}).*(@.*)/, '$1***$2') : '?'
    console.log(`   Host: ${env.emailHost} Port: ${env.emailPort} User: ${maskUser}`)
    return true
  } catch (err) {
    console.error('❌ Email server connection failed:', err.message)
    if (err.code === 'EAUTH') {
      console.error('   → ใช้ Gmail App Password (16 ตัว) ไม่ใช่รหัสผ่านบัญชี: https://myaccount.google.com/apppasswords')
    }
    if (err.code === 'ECONNECTION' || err.code === 'ETIMEDOUT') {
      console.error('   → ตรวจสอบ EMAIL_HOST (smtp.gmail.com) และเครือข่าย')
    }
    return false
  }
}

// แปลง HTML เป็น plain text ที่ดีขึ้น
const htmlToText = (html) => {
  let text = html
    .replace(/<style[^>]*>.*?<\/style>/gis, '')
    .replace(/<script[^>]*>.*?<\/script>/gis, '')
    .replace(/<br\s*\/?>/gi, '\n')
    .replace(/<\/p>/gi, '\n\n')
    .replace(/<\/div>/gi, '\n')
    .replace(/<\/h[1-6]>/gi, '\n\n')
    .replace(/<a[^>]*href=["']([^"']+)["'][^>]*>([^<]+)<\/a>/gi, '$2 ($1)')
    .replace(/<strong[^>]*>([^<]+)<\/strong>/gi, '$1')
    .replace(/<[^>]+>/g, '')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/\n{3,}/g, '\n\n')
    .trim()
  
  return text
}

// สร้าง Message-ID ที่ถูกต้อง
const generateMessageId = () => {
  const domain = env.emailUser?.split('@')[1] || 'cmusharecycle.local'
  const timestamp = Date.now()
  const random = Math.random().toString(36).substring(2, 15)
  return `<${timestamp}.${random}@${domain}>`
}

// ส่งอีเมล (รองรับ Resend หรือ SMTP)
// `text` is optional — pass pre-written plain text for better deliverability.
// If omitted, plain text is auto-generated by stripping HTML tags.
export const sendEmail = async ({ to, subject, html, text }) => {
  const plainText = text || htmlToText(html)

  if (USE_MOCK_EMAIL) {
    return mockSendEmail({ to, subject, text: plainText, html })
  }

  // --- Resend — ให้ความสำคัญก่อนเมื่อมี API key ---
  if (useResend && resendClient) {
    const fromEmail = env.emailFrom?.includes('@') ? env.emailFrom : 'onboarding@resend.dev'
    const fromDisplay = `"CMU ShareCycle" <${fromEmail}>`
    try {
      const { data, error } = await resendClient.emails.send({
        from: fromDisplay,
        to: [to],
        subject,
        html,
        text: plainText,
      })
      if (error) {
        console.error('[RESEND] Send failed:')
        console.error('  error.name      :', error.name)
        console.error('  error.message   :', error.message)
        console.error('  error.statusCode:', error.statusCode ?? null)
        if (process.env.NODE_ENV !== 'production') {
          console.error('  raw error object:', JSON.stringify(error, null, 2))
        }
        return {
          messageId: null,
          accepted: [],
          rejected: [to],
          error: error.message,
          providerError: { name: error.name, statusCode: error.statusCode ?? null },
        }
      }
      console.log('[RESEND] Email sent:', data?.id, '→', to)
      return { messageId: data?.id, accepted: [to], rejected: [] }
    } catch (err) {
      console.error('[RESEND] Unexpected exception:')
      console.error('  error.name      :', err.name)
      console.error('  error.message   :', err.message)
      console.error('  error.statusCode:', err.statusCode ?? err.status ?? null)
      console.error('  error.code      :', err.code ?? null)
      return { messageId: null, accepted: [], rejected: [to], error: err.message }
    }
  }

  // --- SMTP (Gmail → @cmu.ac.th) ---
  if (hasSmtpConfig && transporter) {
    try {
      const fromEmail = env.emailFrom?.includes('@') ? env.emailFrom : env.emailUser
      const info = await transporter.sendMail({
        from: `"CMU ShareCycle" <${fromEmail}>`,
        to,
        replyTo: fromEmail,
        subject,
        html,
        text: plainText,
        // nodemailer auto-sets Date and Message-ID — do not override them here,
        // duplicate headers trigger spam filters in Outlook/Exchange.
        headers: {
          'X-Mailer': 'CMU ShareCycle',
          'X-Priority': '3',
          'Organization': 'Chiang Mai University',
        },
      })
      console.log('Email sent via SMTP:', info.messageId, '→', to)
      return info
    } catch (err) {
      console.error('[SMTP] Send failed:')
      console.error('  error.name      :', err.name)
      console.error('  error.message   :', err.message)
      console.error('  error.code      :', err.code ?? null)
      console.error('  error.response  :', err.response ?? null)
      console.error('  error.responseCode:', err.responseCode ?? null)
      return { messageId: null, accepted: [], rejected: [to], error: err.message }
    }
  }

  return mockSendEmail({ to, subject, text: plainText, html })
}

// รายงานสถานะ email service (ใช้ใน health/diagnostic endpoint)
export const getEmailConfig = () => {
  const mode = USE_MOCK_EMAIL ? 'mock' : useResend ? 'resend' : hasSmtpConfig ? 'smtp' : 'mock'
  const masked = (v) => (v ? v.replace(/(.{2}).*(@.*)/, '$1***$2') : null)
  return {
    mode,
    smtp: {
      host: env.emailHost || null,
      port: env.emailPort || null,
      user: masked(env.emailUser),
      from: masked(env.emailFrom),
      configured: Boolean(hasSmtpConfig),
    },
    resend: {
      configured: Boolean(useResend),
      keyPrefix: env.resendApiKey ? env.resendApiKey.slice(0, 6) + '...' : null,
    },
    mock: USE_MOCK_EMAIL,
  }
}

// ส่งอีเมลทดสอบ
export const sendTestEmail = async (to) => {
  return sendEmail({
    to,
    subject: 'Email delivery test — CMU ShareCycle',
    html: `<p style="font-family:Arial,Helvetica,sans-serif;font-size:14px;">This is a test message from CMU ShareCycle. If you received this, the email transport is working correctly.</p>`,
    text: 'This is a test message from CMU ShareCycle. If you received this, the email transport is working correctly.',
  })
}
