server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  include /etc/nginx/mime.types;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /static/ {
    add_header Cache-Control "public, max-age=31536000, immutable";
  }
}
